export const USER_REGISTER_IN_PROGRESS = "USER_REGISTER_IN_PROGRESS";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

export const USER_LOGIN_IN_PROGRESS = "USER_LOGIN_IN_PROGRESS";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const FETCH_EVENT_IN_PROGRESS = "FETCH_EVENT_IN_PROGRESS";
export const FETCH_EVENT_SUCCESS = "FETCH_EVENT_SUCCESS";
export const FETCH_EVENT_FAILED = "FETCH_EVENT_FAILED";

export const CREATE_EVENT_IN_PROGRESS = "CREATE_EVENT_IN_PROGRESS";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAILED = "CREATE_EVENT_FAILED";

export const DELETE_EVENT_IN_PROGRESS = "DELETE_EVENT_IN_PROGRESS";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILED = "DELETE_EVENT_FAILED";

export const EDIT_EVENT_IN_PROGRESS = "EDIT_EVENT_IN_PROGRESS";
export const EDIT_EVENT_SUCCESS = "EDIT_EVENT_SUCCESS";
export const EDIT_EVENT_FAILED = "EDIT_EVENT_FAILED";
